### ISSUE TITLE
Old fs doesn't listen for ATTRIB events

### ISSUE THREAD

**Issue by ryansch** [phoenixframework/phoenix_live_reload#54]
I'm using dinghy with fsevents_to_vm to run my phoenix container.  It basically touches files in the VM via ssh to force inotify events.  The 0.9.1 fs version pinned in https://github.com/phoenixframework/phoenix_live_reload/commit/e54bf6fb301436797ff589e0b76a047bb79b6870 doesn't listen for the ATTRIB events that come out of this setup but the 2.12.0 version does.

This completely breaks live reload in my setup.

**Comment by chrismccord** [comment]
We're locked on an older version of fs because of undiagnosed rebar build issues folks were experiencing on 2.12.x.

Also, there are known issues with containers on both live_reload as well as recompilation in general so this is not something we plan to tackle right away. Long term, we're moving away from fs and you should able to take this approach, but it's not something we're prioritizing at the moment.  Thanks!
